
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - data_volume:/app/data  # Persist CSV file
    environment:
      - FLASK_ENV=development
      
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://192.168.0.238:5000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map Nginx to port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  data_volume:  # Define a persistent volume